# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         Biblio-Thesaurus
version:      0.24
version_from: lib/Biblio/Thesaurus.pm
installdirs:  site
requires:
    Storable:                      1.0006
    Test::More:                    0

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
