--- #YAML:1.0
name:                Biblio-Thesaurus
version:             0.28
abstract:            ~
license:             ~
generated_by:        ExtUtils::MakeMaker version 6.32
distribution_type:   module
requires:     
    Storable:                      1.0006
    Test::More:                    0
    XML::TMX:                      0.12
meta-spec:
    url:     http://module-build.sourceforge.net/META-spec-v1.2.html
    version: 1.2
